CREATE DATABASE IF NOT EXISTS gym;
USE gym;

-- Drop tables if they exist
DROP TABLE IF EXISTS CALORIES_MEAL;
DROP TABLE IF EXISTS CALORIES;
DROP TABLE IF EXISTS MEAL;
DROP TABLE IF EXISTS USERS;

-- Create USERS table
CREATE TABLE USERS
(
    USERNAME VARCHAR(32) UNIQUE NOT NULL,
    EMAIL VARCHAR(319) UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL,
    PRIMARY KEY(USERNAME)
);

-- Create MEAL table
CREATE TABLE MEAL
(
    MEAL_ID INT PRIMARY KEY,
    ITEM VARCHAR(255),
    CALORIES INT NOT NULL,
);

-- Create CALORIES table
CREATE TABLE CALORIES
(
    CALORIES_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEAL_ID INT,
    USERNAME VARCHAR(32) NOT NULL,
    DATE DATE NOT NULL,
    FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME),
    FOREIGN KEY(MEAL_ID) REFERENCES MEAL(MEAL_ID)
);

-- Create CALORIES_MEAL table
CREATE TABLE CALORIES_MEAL
(
    CALORIES_ID INT,
    MEAL_ID INT,
    FOREIGN KEY(CALORIES_ID) REFERENCES CALORIES(CALORIES_ID),
    FOREIGN KEY(MEAL_ID) REFERENCES MEAL(MEAL_ID)
);